#!/usr/bin/env python3

# Simple webserver that serves content from the root folder

import os
import sys
import http.server
import socketserver
import logging as log

WEB_ROOT = os.path.abspath(os.path.dirname(__file__)) + '/root'
WEB_PORT = 8080


# Setup logging.
root = log.getLogger()
root.setLevel(log.DEBUG)
handler = log.StreamHandler(sys.stdout)
handler.setLevel(log.DEBUG)
formatter = log.Formatter('%(asctime)s - %(name)s - %(levelname)s - %(message)s')
handler.setFormatter(formatter)
root.addHandler(handler)


def serve_web(web_dir=WEB_ROOT, web_port=WEB_PORT):
    # Set the current directory to the folder.
    os.chdir(web_dir)

    # Create the request handler.
    Handler = http.server.SimpleHTTPRequestHandler

    # Create the TCP server.
    with socketserver.TCPServer(("", web_port), Handler) as httpd:
        log.info(f"Serving {web_dir} on http://127.0.0.1:{web_port}/")
        httpd.serve_forever()


if __name__ == "__main__":
    serve_web()